# Generated by Django 5.2 on 2025-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
