name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # ou a branch que você usa no deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via PythonAnywhere API
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/<SEU_USERNAME>/webapps/<SEU_DOMINIO>.pythonanywhere.com/reload/ \
          -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}"
